//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsEventosUG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Matricula
    {
        public int id_materia { get; set; }
        public int id_docente { get; set; }
        public int id_matricula { get; set; }
        public int id_curso { get; set; }
        public int estado_materia { get; set; }
    
        public virtual Cabecera_Matricula Cabecera_Matricula { get; set; }
        public virtual Cursos Cursos { get; set; }
        public virtual Docentes Docentes { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Materias Materias { get; set; }
    }
}
