//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsEventosUG.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbEventosUGEntities : DbContext
    {
        public dbEventosUGEntities()
            : base("name=dbEventosUGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrativo> Administrativo { get; set; }
        public virtual DbSet<Cabecera_Matricula> Cabecera_Matricula { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<Catalogo_Preferencias> Catalogo_Preferencias { get; set; }
        public virtual DbSet<Cursos> Cursos { get; set; }
        public virtual DbSet<Docentes> Docentes { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Estudiantes> Estudiantes { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Facultad> Facultad { get; set; }
        public virtual DbSet<Materias> Materias { get; set; }
        public virtual DbSet<Perfiles> Perfiles { get; set; }
        public virtual DbSet<Preferencia> Preferencia { get; set; }
        public virtual DbSet<Ubicacion> Ubicacion { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Detalle_Matricula> Detalle_Matricula { get; set; }
    
        public virtual ObjectResult<spConsultarLogin_Result> spConsultarLogin(string correo, string clave)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarLogin_Result>("spConsultarLogin", correoParameter, claveParameter);
        }
    
        public virtual int spInsertarEvento(Nullable<int> id_preferencia, string titulo, string detalle, Nullable<System.DateTime> fecha_inicio, Nullable<System.DateTime> fecha_fin, Nullable<int> usuario_creacion)
        {
            var id_preferenciaParameter = id_preferencia.HasValue ?
                new ObjectParameter("id_preferencia", id_preferencia) :
                new ObjectParameter("id_preferencia", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("Detalle", detalle) :
                new ObjectParameter("Detalle", typeof(string));
    
            var fecha_inicioParameter = fecha_inicio.HasValue ?
                new ObjectParameter("fecha_inicio", fecha_inicio) :
                new ObjectParameter("fecha_inicio", typeof(System.DateTime));
    
            var fecha_finParameter = fecha_fin.HasValue ?
                new ObjectParameter("fecha_fin", fecha_fin) :
                new ObjectParameter("fecha_fin", typeof(System.DateTime));
    
            var usuario_creacionParameter = usuario_creacion.HasValue ?
                new ObjectParameter("usuario_creacion", usuario_creacion) :
                new ObjectParameter("usuario_creacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInsertarEvento", id_preferenciaParameter, tituloParameter, detalleParameter, fecha_inicioParameter, fecha_finParameter, usuario_creacionParameter);
        }
    
        public virtual ObjectResult<spConsultarEventos_Result> spConsultarEventos(Nullable<int> id_usuario, Nullable<int> id_evento)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var id_eventoParameter = id_evento.HasValue ?
                new ObjectParameter("id_evento", id_evento) :
                new ObjectParameter("id_evento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarEventos_Result>("spConsultarEventos", id_usuarioParameter, id_eventoParameter);
        }
    
        public virtual ObjectResult<spConsultarPreferencias_Result> spConsultarPreferencias()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarPreferencias_Result>("spConsultarPreferencias");
        }
    
        public virtual ObjectResult<spConsultarPreferenciasIndividual_Result> spConsultarPreferenciasIndividual(Nullable<int> id_uduario)
        {
            var id_uduarioParameter = id_uduario.HasValue ?
                new ObjectParameter("id_uduario", id_uduario) :
                new ObjectParameter("id_uduario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultarPreferenciasIndividual_Result>("spConsultarPreferenciasIndividual", id_uduarioParameter);
        }
    }
}
