//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsEventosUG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ubicacion
    {
        public int id_ubicacion { get; set; }
        public int id_usuario { get; set; }
        public double actual_lat { get; set; }
        public double actual_long { get; set; }
        public string actual_ubicacion { get; set; }
        public double temp_lat { get; set; }
        public double temp_long { get; set; }
        public string temp_ubicacion { get; set; }
        public int estado { get; set; }
    
        public virtual Estados Estados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
